"""
Integration tests for the NDVI change detection module.

Run:
    cd backend
    python -m pytest tests/test_change.py -v

Fixtures are generated by running:
    python tests/make_fixtures.py
"""
import pytest
from pathlib import Path

FIXTURES = Path(__file__).parent / "fixtures"


def _require_fixtures() -> None:
    needed = ["before_4band.tif", "after_4band.tif", "before_ndvi.tif", "after_ndvi.tif"]
    missing = [f for f in needed if not (FIXTURES / f).exists()]
    if missing:
        pytest.skip(f"Fixtures missing: {missing}. Run `python tests/make_fixtures.py` first.")


# ── 4-band Sentinel-2 style ───────────────────────────────────────────────────

def test_4band_returns_expected_keys():
    _require_fixtures()
    from app.eo.change import run_change_detection

    result = run_change_detection(
        str(FIXTURES / "before_4band.tif"),
        str(FIXTURES / "after_4band.tif"),
    )
    expected_keys = {
        "change_pct", "vegetation_loss_pct", "vegetation_gain_pct",
        "water_change_pct", "urban_expansion_pct", "bare_soil_pct",
        "ndvi_before", "ndvi_after", "ndvi_delta", "severity", "summary",
    }
    assert expected_keys == set(result.keys())


def test_4band_ndvi_values_in_range():
    _require_fixtures()
    from app.eo.change import run_change_detection

    r = run_change_detection(
        str(FIXTURES / "before_4band.tif"),
        str(FIXTURES / "after_4band.tif"),
    )
    assert -1.0 <= r["ndvi_before"] <= 1.0
    assert -1.0 <= r["ndvi_after"] <= 1.0


def test_4band_detects_vegetation_loss():
    """After NIR is ~65% of before → expect meaningful veg loss."""
    _require_fixtures()
    from app.eo.change import run_change_detection

    r = run_change_detection(
        str(FIXTURES / "before_4band.tif"),
        str(FIXTURES / "after_4band.tif"),
    )
    assert r["ndvi_delta"] < 0, "Expected negative NDVI delta (vegetation loss)"
    assert r["vegetation_loss_pct"] > 0


def test_4band_severity_is_valid():
    _require_fixtures()
    from app.eo.change import run_change_detection

    r = run_change_detection(
        str(FIXTURES / "before_4band.tif"),
        str(FIXTURES / "after_4band.tif"),
    )
    assert r["severity"] in {"low", "medium", "high", "critical"}


def test_4band_summary_is_non_empty_string():
    _require_fixtures()
    from app.eo.change import run_change_detection

    r = run_change_detection(
        str(FIXTURES / "before_4band.tif"),
        str(FIXTURES / "after_4band.tif"),
    )
    assert isinstance(r["summary"], str) and len(r["summary"]) > 10


# ── 1-band pre-computed NDVI ──────────────────────────────────────────────────

def test_1band_ndvi_works():
    _require_fixtures()
    from app.eo.change import run_change_detection

    r = run_change_detection(
        str(FIXTURES / "before_ndvi.tif"),
        str(FIXTURES / "after_ndvi.tif"),
    )
    assert r["ndvi_delta"] < 0, "Pre-computed NDVI: after < before by design"
    assert r["change_pct"] >= 0


# ── Error handling ────────────────────────────────────────────────────────────

def test_same_file_produces_zero_change():
    """Using the same file twice should yield ~0 change."""
    _require_fixtures()
    from app.eo.change import run_change_detection

    r = run_change_detection(
        str(FIXTURES / "before_4band.tif"),
        str(FIXTURES / "before_4band.tif"),
    )
    assert r["change_pct"] == pytest.approx(0.0, abs=1.0)
    assert r["ndvi_delta"] == pytest.approx(0.0, abs=0.01)


def test_missing_file_raises():
    from app.eo.change import run_change_detection
    import rasterio

    with pytest.raises((FileNotFoundError, rasterio.errors.RasterioIOError)):
        run_change_detection("/nonexistent/before.tif", "/nonexistent/after.tif")
